### ISSUE TITLE
Dirty ratio 고정 방법

### ISSUE THREAD

**Issue by YoungHoonJun** [EMDC-OS/mg-lru#1]
Dirty ratio를 상황에 따라 고정하는게 아니라, 특정 값으로 설정한 뒤에 성능을 측정하고 싶습니다. 가능한 방법이 있을까요?

**Comment by J-S-Kim** [comment]
아니요. 기존에 dirty_ratio 파일이 이미 고정하여 실험하는 용도로 되어있기 때문에 수정한 커널에서는 
별도로 고정하는 기능은 구현하지 않았습니다.

필요하시다면, 기존 커널에서 고정하여 실험하실 수 있습니다.
