### ISSUE TITLE
Kernel Build Error

### ISSUE THREAD

**Issue by gwanjong** [EMDC-OS/mg-lru#5]
![image](https://github.com/user-attachments/assets/359d1411-680b-43ec-bf79-dfae36aec8f6)

When running make olddefconfig and make, I encountered an error as shown in the uploaded image.

Could there be anything I missed during the kernel build process? 

Thanks for your support in advance!

**Comment by J-S-Kim** [comment]
In this case, try removing the line referencing debian/canonical-certs.pem in the .config file generated inside the kernel directory, then attempt to rebuild.

Thank you.
